config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'bands#index'

  resources :chat_rooms, only: [:new, :create, :show, :index]
  
  resources :uploads, only: [:new, :create, :show, :index]
  
  resources :bands, only: [:new, :create, :edit, :update, :show, :index] do
    member do
      get 'join'
      get 'invite'
      post 'send_invitation'
    end
  end

  resources :folders, only: [:new, :create, :edit, :update, :show, :index]
  
  resources :gigs do
    member do
      get 'copy'
    end
  end
  
  resources :tasks, only: [:new, :create, :edit, :update, :show, :index]

  namespace :admin do
    # Distinct from the normal dashboards#index!
    root 'dashboards#index'

    resources :dashboards, only: [:index]
    resources :bands, only: [:index, :show]
    resources :users, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :band
  has_many :messages, dependent: :destroy
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chat_room = ChatRoom.find_by(id: params[:id])

    messages = @chat_room.messages.all.order(:created_at)
    @messages_by_date = messages.group_by { |m| m.created_at.to_date }

    @message = Message.new
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'New chat room added.'

      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:name)
  end

end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<h1>Chat Rooms</h1>

<p class="lead"><%= link_to 'New Chat Room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add Chat Room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Go!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<div class="page-content">  
  <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <div class="date_message">
      <%= @band.name %>
    </div>

    <% @messages_by_date.each do |messages| %>
      <div class="date_message">
        Messages from <%= messages[0].strftime('%a, %b %e, %Y') %>
      </div>

      <%= render messages[1] %>
    <% end %>
  </div>  
</div>

<div class="page-footer">
  <div id="new_message" class="container" style="padding: 5px;">
    <%= form_for @message, url: '#' do |f| %>  
      <div class="field has-addons">
        <div class="control is-expanded">
          <div class="is-fullwidth">
            <%= f.text_field :body, class: 'input is-primary' %>
          </div>
        </div>
        <div class="control">
          <%= f.submit "Send", class: 'button is-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>