config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'bands#index'

  resources :chat_rooms, only: [:new, :create, :show, :index]
  
  resources :uploads, only: [:new, :create, :show, :index]
  
  resources :bands, only: [:new, :create, :edit, :update, :show, :index] do
    member do
      get 'join'
      get 'invite'
      post 'send_invitation'
    end
  end

  resources :folders, only: [:new, :create, :edit, :update, :show, :index]
  
  resources :gigs do
    member do
      get 'copy'
    end
  end
  
  resources :tasks, only: [:new, :create, :edit, :update, :show, :index]

  namespace :admin do
    # Distinct from the normal dashboards#index!
    root 'dashboards#index'

    resources :dashboards, only: [:index]
    resources :bands, only: [:index, :show]
    resources :users, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :band
  belongs_to :responsibile_user, optional: true, class_name: 'user'
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = @band.tasks.all.order(:position)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.band = @band

    if @task.save
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :due_date, :responsible_user_id)
  end
end

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :responsible_user_id %>
    <%= f.collection_select(:responsible_user_id, @band.users.all, :id, :email, {include_blank: true}, {class: 'form-control'}) %>
  </div>

  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/tasks/_task.html.erb
<li class='gig'>
  <hr/>
  <%= link_to task do %>
    <div class="row">
      <div class="col-md-2">
        <%= task.responsibile_user.id if task.responsibile_user %>
      </div>
      <div class="col-md-10">        
      <%= task.description %>
      </div>      
    </div>  
  <% end %>
</li>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Edit Task</h1>
  </div>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Tasks</h1>
  </div>

  <div class="col-sm-6 text-right">
    <%= link_to "Create a new Task", new_task_path, class: 'btn btn-primary' %>
  </div>
</div>

<ul>
  <%= render @tasks %>
</ul>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>New Task</h1>
  </div>  
</div> 

<%= render 'form' %>