config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'bands#index'

  resources :chat_rooms, only: [:new, :create, :show, :index]
  
  resources :uploads, only: [:new, :create, :show, :index]
  
  resources :bands, only: [:new, :create, :edit, :update, :show, :index] do
    member do
      get 'join'
      get 'invite'
      post 'send_invitation'
    end
  end

  resources :folders, only: [:new, :create, :edit, :update, :show, :index]
  
  resources :gigs do
    member do
      get 'copy'
    end
  end
  
  resources :tasks, only: [:new, :create, :edit, :update, :show, :index]

  namespace :admin do
    # Distinct from the normal dashboards#index!
    root 'dashboards#index'

    resources :dashboards, only: [:index]
    resources :bands, only: [:index, :show]
    resources :users, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_members
  has_many :users, through: :band_members
  has_many :gigs
  has_many :tasks

  has_one :chat_room
  has_one :folder

  after_create_commit :create_resources

  def create_resources
    # Create the default chat room for the band
    chat_room = ChatRoom.create(name: self.name)
    self.chat_room = chat_room
    self.save!

    # Likewise create the default folder for the band
    folder = Folder.create(name: self.name)
    self.folder = folder
    self.save!
  end

  def add_user_to_band(user_id)
    user = User.find_by(id: user_id)
    if !has_member?(user.id)
      BandMember.create!(
        band: @band,
        user_id: user
      )
    end
  end

  def has_member?(user_id)
    band_members = self.users.where(id: user_id)
    if band_members.size > 0 then
      true
    else
      false
    end
  end
end

app/controllers/admin/bands_controller.rb
class Admin::BandsController < Admin::AdminController
  def index
    @bands = Band.all
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :get_band, only: [:show, :join, :invite]
  
  def index
    # Get all the bands that your user is in
    @bands = current_user.bands.all

    # If you've got more than one band, redirect to the session store band
    # If you're only in one band, redirect to that band page
    # If you're not in any bands, you should set one up
    if @bands.size > 0       
      redirect_to @band
    else # @bands.size < 1
      redirect_to new_band_path
    end
  end

  def show
    session[:current_band_id] = @band.id
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      @band.add_user_to_band(current_user.id)

      flash[:success] = 'New band added.'

      redirect_to @band
    else
      @band.errors.each do |e|
        puts e
      end
      render 'new'
    end
  end

  def join
    @band.add_user_to_band(current_user.id)

    redirect_to @band
  end

  def invite
  end

  def send_invitation
    email = params[:email]
    message = params[:message]

    user = User.invite!(email: email)
    # We do this in anticipation of the user accepting
    @band.add_user_to_band(user.id)

    flash[:info] = "An invitation has been sent to #{email} to join #{@band.name}"

    redirect_to @band
  end

  private

  def get_band
    @band = Band.find_by(id: params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/views/bands/index.html.erb
My Bands

app/views/bands/invite.html.erb
Invite somebody!

<%= form_with url: send_invitation_band_path(@band) do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_field :message, class: 'form-control' %>
  </div>

  <%= f.submit %>
<% end %>

app/views/bands/new.html.erb
<h1>You need to set up a new band!</h1>

<%= form_for @band do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Go!", class: 'btn btn-primary' %>
<% end %>

app/views/bands/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <p class="title">
      <%= @band.name %>
    </p>
  </div>      
</section>

<h3>Band Members</h3>
<ul class="band-members">
  <% @band.users.uniq.each do |user| %>
    <li>
      <% if user == current_user %>
        <%= link_to user.email, edit_registration_path(user) %> (you!)
      <% else %>
        <%= user.email %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to "Invite a new member", invite_band_path(@band) %>

<h3>Activity</h3>