config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'bands#index'

  resources :chat_rooms, only: [:new, :create, :show, :index]
  
  resources :uploads, only: [:new, :create, :show, :index]
  
  resources :bands, only: [:new, :create, :edit, :update, :show, :index] do
    member do
      get 'join'
      get 'invite'
      post 'send_invitation'
    end
  end

  resources :folders, only: [:new, :create, :edit, :update, :show, :index]
  
  resources :gigs do
    member do
      get 'copy'
    end
  end
  
  resources :tasks, only: [:new, :create, :edit, :update, :show, :index]

  namespace :admin do
    # Distinct from the normal dashboards#index!
    root 'dashboards#index'

    resources :dashboards, only: [:index]
    resources :bands, only: [:index, :show]
    resources :users, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user

  after_create_commit :create_message

  def create_message
    puts "create a new message"

    message_body = "uploaded a new file #{self.name}!"
    chat_room = ChatRoom.find_by(id: 1)
    message = Message.create!(
                         body: message_body,
                         chat_room: chat_room,
                         user: self.user
    )
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = current_user.uploads.build(upload_params)
    if @upload.save
      flash[:success] = 'New @upload added.'

      redirect_to uploads_path
    else
      render 'new'
    end
  end

  private

  def upload_params
    params.require(:upload).permit(:name)
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_upload.html.erb
<div>
  <%= upload.name %> / <%= upload.description %> / <%= upload.user.email %> / <%= upload.created_at %>
</div>

app/views/uploads/index.html.erb
<h1>Uploads</h1>

<p class="lead"><%= link_to 'New Upload', new_upload_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @uploads %>
</ul>

app/views/uploads/new.html.erb
<h1>Add Upload</h1>

<%= form_for @upload do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <%= f.submit "Go!", class: 'btn btn-primary' %>
<% end %>